package com.voucher.manage.tkmapper.entity;

import org.springframework.data.annotation.Id;

import javax.persistence.Table;
import java.util.Date;

@Table(name = "`usersinfo`")
public class Usersinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersinfo.open_id
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    @Id
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersinfo.phone
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersinfo.name
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersinfo.headship
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    private String headship;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersinfo.email
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersinfo.address
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersinfo.rank
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersinfo.up_time
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    private Date upTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersinfo.open_id
     *
     * @return the value of usersinfo.open_id
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersinfo.open_id
     *
     * @param openId the value for usersinfo.open_id
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersinfo.phone
     *
     * @return the value of usersinfo.phone
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersinfo.phone
     *
     * @param phone the value for usersinfo.phone
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersinfo.name
     *
     * @return the value of usersinfo.name
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersinfo.name
     *
     * @param name the value for usersinfo.name
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersinfo.headship
     *
     * @return the value of usersinfo.headship
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public String getHeadship() {
        return headship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersinfo.headship
     *
     * @param headship the value for usersinfo.headship
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public void setHeadship(String headship) {
        this.headship = headship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersinfo.email
     *
     * @return the value of usersinfo.email
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersinfo.email
     *
     * @param email the value for usersinfo.email
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersinfo.address
     *
     * @return the value of usersinfo.address
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersinfo.address
     *
     * @param address the value for usersinfo.address
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersinfo.rank
     *
     * @return the value of usersinfo.rank
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersinfo.rank
     *
     * @param rank the value for usersinfo.rank
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public void setRank(String rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersinfo.up_time
     *
     * @return the value of usersinfo.up_time
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersinfo.up_time
     *
     * @param upTime the value for usersinfo.up_time
     *
     * @mbg.generated Thu Feb 21 17:31:41 CST 2019
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    @Override
    public String toString() {
        return "Usersinfo{" +
                "openId='" + openId + '\'' +
                ", phone='" + phone + '\'' +
                ", name='" + name + '\'' +
                ", headship='" + headship + '\'' +
                ", email='" + email + '\'' +
                ", address='" + address + '\'' +
                ", rank='" + rank + '\'' +
                ", upTime=" + upTime +
                '}';
    }
}